# DATASOURCE CONFIGURATION
#spring.datasource.url=jdbc:postgresql://db.fgfealmzirggrvdwghfh.supabase.co:5432/postgres
spring.datasource.url=jdbc:postgresql://crossover.proxy.rlwy.net:27323/railway
spring.datasource.username=postgres
spring.datasource.password=lEtNweONySDDdyxMRXuWVjdRSuTqMuju
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource..connection-init-sql=SET TIME ZONE 'Asia/Jakarta'

spring.datasource.minimum-idle=5
spring.datasource.maximumPoolSize=20
spring.datasource.connection-timeout=120000
spring.datasource.leak-detection-threshold=300000

spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# SERVLET CONFIGURATION
server.port=8080
server.servlet.context-path=/api/spk
spring.application.name=bansos

logging.level.root=DEBUG